<?xml version='1.1' encoding='UTF-8'?>
<hudson.maven.MavenModuleSetBuild plugin="maven-plugin@3.5">
  <actions>
    <hudson.model.CauseAction>
      <causeBag class="linked-hash-map">
        <entry>
          <hudson.model.Cause_-UserIdCause>
            <userId>admin</userId>
          </hudson.model.Cause_-UserIdCause>
          <int>1</int>
        </entry>
      </causeBag>
    </hudson.model.CauseAction>
    <hudson.plugins.chucknorris.RoundhouseAction plugin="chucknorris@1.2">
      <mStyle>BAD_ASS</mStyle>
      <mFact>Chuck Norris does not use exceptions when programming. He has not been able to identify any of his code that is not exceptional.</mFact>
    </hudson.plugins.chucknorris.RoundhouseAction>
  </actions>
  <queueId>21</queueId>
  <timestamp>1586012694973</timestamp>
  <startTime>1586012694977</startTime>
  <result>FAILURE</result>
  <duration>3306</duration>
  <charset>UTF-8</charset>
  <keepLog>false</keepLog>
  <builtOn></builtOn>
  <workspace>/var/jenkins_home/workspace/helloworld-abatura-maven-build</workspace>
  <hudsonVersion>2.222.1</hudsonVersion>
  <scm class="hudson.scm.NullChangeLogParser"/>
  <culprits class="com.google.common.collect.EmptyImmutableSortedSet"/>
</hudson.maven.MavenModuleSetBuild>